## Add route53 
myDNSOne:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName: example.com.
    Comment: Weighted RR for my frontends.
    RecordSets:
    - Name: mysite.example.com.
      Type: CNAME
      TTL: '900'
      SetIdentifier: Frontend One
      Weight: '4'
      ResourceRecords:
      - example-ec2.amazonaws.com
    - Name: mysite.example.com.
      Type: CNAME
      TTL: '900'
      SetIdentifier: Frontend Two
      Weight: '6'
      ResourceRecords:
      - example-ec2-larger.amazonaws.com


## Add certificate (2 certs)
Type: AWS::CertificateManager::Certificate
Properties: 
  CertificateAuthorityArn: String
  CertificateTransparencyLoggingPreference: String
  DomainName: String
  DomainValidationOptions: 
    - DomainValidationOption
  SubjectAlternativeNames: 
    - String
  Tags: 
    - Tag
  ValidationMethod: String


Type: AWS::CertificateManager::Certificate
Properties: 
  CertificateAuthorityArn: String
  CertificateTransparencyLoggingPreference: String
  DomainName: String
  DomainValidationOptions: 
    - DomainValidationOption
  SubjectAlternativeNames: 
    - String
  Tags: 
    - Tag
  ValidationMethod: String








# Type: AWS::Route53::RecordSet
# Properties: 
#   AliasTarget: 
#     AliasTarget
#   Comment: String
#   Failover: String
#   GeoLocation: 
#     GeoLocation
#   HealthCheckId: String
#   HostedZoneId: String
#   HostedZoneName: String
#   MultiValueAnswer: Boolean
#   Name: String
#   Region: String
#   ResourceRecords: 
#     - String
#   SetIdentifier: String
#   TTL: String
#   Type: String
#   Weight: Integer





